# Generated by Django 5.1.4 on 2025-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_email_alter_profile_mobile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('role', models.CharField(choices=[('1', 'нападающий'), ('2', 'защитник'), ('3', 'вратарь')], default='1')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
