# Generated by Django 5.1.4 on 2025-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_testbalancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbalancer',
            name='role',
            field=models.CharField(choices=[('forward', 'нападающий'), ('defender', 'защитник'), ('goalkeeper', 'вратарь')], default='1'),
        ),
    ]
