# Generated by Django 5.1.4 on 2025-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_testbalancer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Micromatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('matchRating', models.IntegerField()),
                ('team1_players', models.JSONField()),
                ('team2_players', models.JSONField()),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='testbalancer',
            name='gender',
            field=models.CharField(choices=[('M', 'мужской'), ('W', 'женский')], default='M'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'мужской'), ('W', 'женский')], default='M'),
        ),
        migrations.AlterField(
            model_name='testbalancer',
            name='role',
            field=models.CharField(choices=[('forward', 'нападающий'), ('defender', 'защитник'), ('goalkeeper', 'вратарь')], default='forward'),
        ),
    ]
