# Generated by Django 5.1.4 on 2025-04-25 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_micromatch_testbalancer_gender_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromatch',
            name='match_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
