# Generated by Django 5.1.4 on 2025-04-25 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_micromatch_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micromatch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='micromatch',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='micromatch',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='micromatch',
            name='match_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
