# Generated by Django 5.1.4 on 2025-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_micromatch_id_remove_micromatch_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micromatch',
            name='team1_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='micromatch',
            name='team2_score',
            field=models.IntegerField(null=True),
        ),
    ]
