# Generated by Django 5.1.4 on 2025-04-27 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_micromatch_team1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
