# Generated by Django 5.1.4 on 2025-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_profile_age_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbalancer',
            name='player_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
