# Generated by Django 5.1.4 on 2025-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_testbalancer_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbalancer',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testbalancer',
            name='goals_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testbalancer',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
