# Generated by Django 5.1.4 on 2025-04-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_testbalancer_goals_scored_testbalancer_goals_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announsment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='testbalancer',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
