# Generated by Django 5.1.4 on 2025-05-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_micromatch_team1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('player_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(null=True)),
                ('role', models.CharField(choices=[('forward', 'нападающий'), ('defender', 'защитник'), ('goalkeeper', 'вратарь')], default='forward')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'мужской'), ('W', 'женский')], default='M')),
                ('matches_played', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tour_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('goal_matrix', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='TestBalancer',
        ),
        migrations.AddField(
            model_name='micromatch',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main_app.tournament'),
        ),
    ]
