# Generated by Django 5.1.4 on 2025-05-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_competitor_tournament_delete_testbalancer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='goal_matrix',
            new_name='played_with_matrix',
        ),
    ]
