# Generated by Django 5.1.4 on 2025-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_goal_matrix_tournament_played_with_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='players_pool',
            field=models.JSONField(default=list, null=True),
        ),
    ]
