# Generated by Django 5.1.4 on 2025-05-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_competitor_players_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='players_pool',
        ),
        migrations.CreateModel(
            name='TourGroupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_age_pool', models.CharField()),
                ('group_gender', models.CharField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main_app.competitor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main_app.tournament')),
            ],
        ),
    ]
