# Generated by Django 5.1.4 on 2025-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_competitor_players_pool_tourgroupplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourgroupplayer',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
