# Generated by Django 5.1.4 on 2025-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_tourgroupplayer_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourgroupplayer',
            name='player',
        ),
        migrations.AddField(
            model_name='competitor',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourgroupplayer',
            name='age_spread',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourgroupplayer',
            name='stopped_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourgroupplayer',
            name='group_age_pool',
            field=models.JSONField(default=tuple),
        ),
    ]
