# Generated by Django 5.1.4 on 2025-05-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_tourgroupplayer_player_competitor_group_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourGroupPlayer',
            new_name='TournamentGroup',
        ),
    ]
