# Generated by Django 5.1.4 on 2025-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_tourgroupplayer_tournamentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='start_rating',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
