# Generated by Django 5.1.4 on 2025-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_competitor_start_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='start_rating',
            field=models.IntegerField(null=True),
        ),
    ]
