# Generated by Django 5.1.4 on 2025-05-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_competitor_start_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='micromatch',
            options={'permissions': [('can_save_score', 'Can save match score'), ('can_generate_match', 'Can generate new match')]},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': [('can_start_tour', 'Can start new tournament')]},
        ),
    ]
