# Generated by Django 5.1.4 on 2025-05-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_micromatch_options_alter_tournament_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
