# Generated by Django 5.1.4 on 2025-05-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_profile_category_alter_profile_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('cant_reg_in_tour', 'Cannot register in tournament')]},
        ),
    ]
