# Generated by Django 5.1.4 on 2025-06-07 13:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micromatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[('новичок', 'новичок'), ('любитель', 'любитель'), ('III юношеский', 'III юношеский'), ('II юношеский', 'II юношеский'), ('I юношеский', 'I юношеский'), ('III спортивный', 'III спортивный'), ('II спортивный', 'II спортивный'), ('I спортивный', 'I спортивный'), ('КМС', 'КМС'), ('ГР', 'ГР'), ('МСМК', 'МСМК')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'мужской'), ('W', 'женский')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('forward', 'нападающий'), ('defender', 'защитник'), ('goalkeeper', 'вратарь')], null=True),
        ),
    ]
