# Generated by Django 5.1.4 on 2025-06-09 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_micromatch_created_at_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_ratings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='micromatch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 17, 54, 0, 451123, tzinfo=datetime.timezone.utc)),
        ),
    ]
