# Generated by Django 5.1.4 on 2025-06-10 12:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_profile_previous_ratings_alter_competitor_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='isEnded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='minutes_btwn_groups',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='minutes_btwn_matches',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='playing_groups_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='time_started',
            field=models.TimeField(default=datetime.datetime(2025, 6, 10, 12, 47, 10, 22737, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='micromatch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 12, 47, 10, 23241, tzinfo=datetime.timezone.utc)),
        ),
    ]
