# Generated by Django 5.1.4 on 2025-06-12 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_tournament_isended_tournament_minutes_btwn_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromatch',
            name='isPlayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='micromatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time_started',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
