# Generated by Django 5.1.4 on 2025-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_micromatch_isplayed_alter_micromatch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromatch',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
