# Generated by Django 5.1.4 on 2025-06-13 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_micromatch_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micromatch',
            name='created_at',
        ),
        migrations.AddField(
            model_name='micromatch',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
