# Generated by Django 5.1.4 on 2025-06-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_remove_micromatch_created_at_micromatch_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromatch',
            name='field_num',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
