# Generated by Django 5.1.4 on 2025-06-13 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_micromatch_field_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='minutes_btwn_groups',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='minutes_btwn_matches',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
