# Generated by Django 5.1.4 on 2025-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_alter_tournament_minutes_btwn_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micromatch',
            name='field_num',
            field=models.IntegerField(default=1),
        ),
    ]
