# Generated by Django 5.1.4 on 2025-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_alter_micromatch_field_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
