# Generated by Django 5.1.4 on 2025-06-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_alter_announsment_options_alter_competitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
