# Generated by Django 5.1.4 on 2025-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_profile_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='micromatch',
            name='players_ids',
            field=models.JSONField(default=list, verbose_name='ID игроков'),
        ),
    ]
